// <auto-generated />
namespace HC.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addnewtables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnewtables));
        
        string IMigrationMetadata.Id
        {
            get { return "202207171124381_addnewtables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
