// <auto-generated />
namespace HC.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class product_materialtables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product_materialtables));
        
        string IMigrationMetadata.Id
        {
            get { return "202207311105413_product_material tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
